import React from 'react'
import { makeStyles } from '@material-ui/core/styles';
import Divider from '@material-ui/core/Divider';
import { Container} from 'react-bootstrap';

const useStyles = makeStyles((theme) => ({
  root: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: theme.palette.background.paper,
    color: '#C90F03'
  }
}));

export default function ListDividers() {
  const classes = useStyles();
  return (
      <>
      <Container className="d-flex align-items-center justify-content-center" style={{minHeight:"100vh", padding:'0 0 0 0'}}
      >
            <div className="w-100" style={{maxWidth:"800px" , padding:"20px"}}>
        <center><h3>PRIVACY POLICY</h3></center><br/>
        <p> We know that you care how information about you is used and shared and we appreciate your trust in us to do that carefully and sensibly. By using FoodieVerse, you are accepting and consenting to the practices described in this Privacy Policy and you agree that FoodieVerse may collect, process and use the personal information listed below for the mentioned purposes.</p><br/>
        <h5>Controllers of Personal Information</h5>
        <p> Any personal information provided to or gathered by FoodieVerse under this Privacy Notice will be stored and controlled by FoodieVerse (the data controller/ data fiduciary).</p><br/>
        <h5>What Personal Information About Customers Does FoodieVerse Gather?</h5>
        <p> The information we learn and gather from you, personal or otherwise, is used to register you for FoodieVerse , verify your identity to permit you to use FoodieVerse , undertake transactions (including to facilitate and process payments) in connection with FoodieVerse Pay, communicate with you about FoodieVerse , any promotional offers, services or updates associated with FoodieVerse , and generally maintain your accounts with us. We also use this information to customize your experience and improve FoodieVerse , or to prevent or detect fraud or abuses of FoodieVerse  that are made available to you and to enable third parties to carry out technical, logistical, payment processing or other functions on our behalf.</p>
        <p> Here are the types of information we gather :</p>
        <ul>
            <li>Information You Give Us: We receive and store any information you provide while using FoodieVerse , or give us in any other way. You can choose not to provide certain information, but then you might not be able to use FoodieVerse . We use the information that you provide for such purposes as opening your account, processing your transactions, responding to your requests, providing FoodieVerse , and communicating with you.</li>
            <li>Automatic Information: We receive and store certain types of information whenever you interact with us. For example, like many websites, we use "cookies," and we obtain certain types of information when your web browser accesses our Services. When you interact with a third-party site that uses one of the FoodieVerse  services, such as Pay with FoodieVerse, our servers automatically record information that your browser sends. We may also receive/store information about your location and your mobile device, including a unique identifier for your device. We may use this information for internal analysis and to provide you with location-based services, such as advertising, search results, and other personalized content.</li>
            <li>Our Communications with Users: Among other things, we communicate with users on a regular basis via e-mail, and we communicate by phone to resolve user complaints or investigate suspicious transactions. We also use your e-mail address to send you notices in relation to your use of FoodieVerse , to send information about important changes to FoodieVerse , and to send notices and other disclosures required by law. You agree to receive such communications electronically. We may send you promotional messages about new services, offers or opportunities that may interest you. If you do not want to receive promotional messages or other reminders and e-mails from us, please adjust your communication preferences" under Your Account settings on FoodieVerse. However, we reserve the right to send you notices for customer service reasons, including notices about your account or transactions using FoodieVerse . Also, to help us make e-mails more useful and interesting, we may receive a confirmation when you open or receive e-mail from us. We also compare our customer list to lists received from other companies, in an effort to avoid sending unnecessary messages to our customers.</li>
            <li>Information from Other Sources: We might receive information about you from other sources and add it to our account information. By using or continuing to use FoodieVerse , you agree to our use of your information (including sensitive personal information) in accordance with this Privacy Notice, as may be amended from time to time by us in our discretion. You also agree and consent to us collecting, storing, processing, transferring and sharing information (including sensitive personal information) related to you with third parties or service providers for the purposes as set out in this Privacy Notice.</li>
            <li>We may be required to share the aforesaid information with government authorities and agencies for the purposes of verification of identity or for prevention, detection or investigation, including of cyber incidents, prosecution and punishment of offences. You agree and consent for FoodieVerse to disclose your information, if so required, under applicable law.</li>
        </ul><br/>
        <h5>What About Cookies?</h5>
        <ul>
            <li>Cookies are alphanumeric identifiers that we transfer to your computer's hard drive through your Web browser to enable our systems to recognize your browser so we can recognize you as an FoodieVerse user if you return to use FoodieVerse  using the same computer and browser and to provide features such as Recommended for You, or personalised advertisements on other websites.</li>
            <li>The "Help" portion of the toolbar on most browsers will tell you how to prevent your browser from accepting new cookies, how to have the browser notify you when you receive a new cookie, or how to disable cookies altogether. Additionally, you can disable or delete similar data used by browser add-ons, such as Flash cookies, by changing the add-on's settings or visiting the website of its manufacturer. However, you then may lose the ability to utilize some of the FoodieVerse  features, and we recommend that you leave cookies turned on.</li>
            <li>If you do leave cookies turned on, be sure to sign off when you finish using a shared computer.</li>
        </ul><br/>
        <h5>Does FoodieVerse share the Information it receives?</h5>
        <p>Information about our users is an important part of our business, and we are not in the business of selling it to others. We share customer information only as described below and with the family of companies owned and controlled by FoodieVerse, and that are either subject to this Privacy Notice or follow practices at least as protective as those described in this Privacy Notice.</p><br/>        
        <h5>How Secure is Information About Me?</h5>
        <ul>
            <li>We work to protect the security of personal information during transmission by using Secure Sockets Layer (SSL) software, which encrypts information you input in addition to maintaining security of your information as per the International Standard IS/ISO/IEC 27001 on "Information Technology Security Techniques Information Security Management System-Requirements". We restrict access to your personally identifiable information to employees who need to know that information in order to provide products or Services to you. We maintain physical, electronic and procedural safeguards in connection with the collection, storage and disclosure of personal information (including sensitive personal information). Our security procedures mean that we may occasionally request proof of identity before we disclose personal information to you.</li>
            <li>We reveal only the last four digits of your credit/debit card numbers when confirming an order. Of course, we transmit the entire credit/debit card number to the appropriate credit card company for payment processing.</li>
            <li>It is important for you to take steps to protect against unauthorized access to your account. You should keep confidential your password, security questions, and any other credentials used to access your account (your "Credentials"). The security of your account with FoodieVerse relies on your protection of your Credentials. DO NOT SHARE YOUR CREDENTIALS. If you do share your Credentials with a third party for any reason, the third party may have access to your account and your personal information, and you may be responsible for actions taken using your Credentials. If you believe someone else has obtained access to your Credentials, please change them immediately by logging in to your account and changing your Profile settings, and also contact us right away.</li>
        </ul><br/>
        <h5>What About Third-Party Advertisers and Links to Other Websites?</h5>
        <p>Our Site may include third-party advertising and links to other websites. We do not provide any personally identifiable user information to these advertisers or third-party websites. These third-party websites and advertisers, or Internet advertising companies working on their behalf, sometimes use technology to send (or "serve") the advertisements that appear on the Site directly to your browser. They automatically receive your IP address when this happens. They may also use cookies, JavaScript, web beacons (also known as action tags or single-pixel gifs), and other technologies to measure the effectiveness of their ads and to personalize advertising content. We do not have access to or control over cookies or other features that they may use, and the information practices of these advertisers and third-party websites are not covered by this Privacy Notice. Please contact them directly for more information about their privacy practices.</p><br/>
        <h5>What Information can I Access?</h5>
        <p>FoodieVerse gives you access to information about your account and your interactions with us for the limited purpose of viewing and, in certain cases, updating that information. Information about you may be accessed by logging into your account with FoodieVerse and viewing the "My Account" tab.</p><br/>
        <h5>Are Children Allowed to Use Foodiverse?</h5>
        <p>This is an entirely child-friendly website. Recipes are verified before publishing to ensure that no obscene data is present.</p><br/>
        <h5>Examples of Information Collected</h5>
        <ul>
            <li>Automatic Information - Examples of the information we collect and analyze include the internet protocol (IP) address used to connect your computer to the internet; login; e-mail address; password; computer and connection information such as browser type and version, operating system, and platform; transaction history, which we sometimes aggregate with similar information from other users or Site visitors; the full Uniform Resource Locator (URL) click-stream to, through, and from our Site, including date and time; cookie number; and the phone number you used to call our toll free number. We may also use browser data such as cookies, Flash cookies (also known as Flash Local Shared Objects), or similar data on certain parts of our Site for fraud prevention and other purposes. During some visits we may use software tools such as JavaScript to measure and collect session information, including page response times, download errors, length of visits to certain pages, page interaction information (such as scrolling, clicks, and mouse-overs), and methods used to browse away from the page. When you visit a third-party website that uses one of our Services, your browser may send information such as your page request, URL, IP address, browser type, browser language, the date and time of your request, and your cookie information.</li>
            <li>Information from Other Sources - We might receive information about you from other sources and add it to our account information. Information. For example, information we receive from other sources include: account information, purchase or redemption information and page-view information from some merchants with which we operate co-branded businesses or for which we provide technical, fulfillment, advertising or other services; search term and search result information from some searches conducted through the Web search features offered by FoodieVerse Group Companies, Alexa Internet and A9; search results and links, including paid listings (such as Sponsored Links from Overture); and credit history information from credit bureaus, which we use to help prevent and detect fraud and to offer certain credit or financial services to some customers; in order to protect against potential fraud, we may verify with third party services the information you provide. During the verification process we receive personally identifiable information about you from such services. For example, if you register a credit card or debit card with us, we will use card authorization and fraud screening services to verify that your card information and address matches the information that you supplied to us, and that the card has not been reported as lost or stolen. In addition, we, at our sole discretion and subject to applicable law, reserve the right periodically to retrieve and review a credit report or other credit history information from credit bureaus for any account.</li>
            <li>Information You Can Access - Examples of information you can access easily at our site include up-to-date information regarding recent transactions; personally identifiable information (including name, e-mail, password, communications preferences); payment settings (including credit card information, available FoodieVerse Pay balance and bank account information); e-mail notification settings; recommendations and your profile.</li>
        </ul>
      </div>
      </Container>
    </>
  );
}
